import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { jwtDecode } from "jwt-decode";
import "bootstrap/dist/css/bootstrap.min.css";

function QuizGenerator() {
    const [file, setFile] = useState(null);
    const [quiz, setQuiz] = useState(null);
    const [loading, setLoading] = useState(false);

    const navigate = useNavigate();
    const token = localStorage.getItem("authToken");

    // AUTH CHECK
    useEffect(() => {
        if (!token) return navigate("/login");

        try {
            const decoded = jwtDecode(token);
            const roles = decoded.roles || [];
            if (!roles.includes("Trainer")) navigate("/access-denied");
        } catch (err) {
            localStorage.removeItem("authToken");
            navigate("/login");
        }
    }, [token, navigate]);

    const handleUpload = async () => {
        if (!file) {
            alert("Please select a PDF file first!");
            return;
        }

        const formData = new FormData();
        formData.append("file", file);

        setLoading(true);
        try {
            const res = await fetch("http://localhost:5000/api/upload", {
                method: "POST",
                body: formData,
                headers: {
                    'Authorization': `Bearer ${token}`,
                    "Content-Type": "application/json"
                }, // use if JWT/cookies are needed
            });

            if (!res.ok) {
                const text = await res.text();
                console.error("Upload failed:", text);
                alert("Upload failed. Check backend logs.");
                return;
            }

            const data = await res.json();
            console.log("Quiz generated:", data);
            setQuiz(data); // store backend response (assessments + questions)
        } catch (err) {
            console.error("Fetch error:", err);
            alert("An error occurred. Check console.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="container-fluid" style={{ height: "100vh" }}>
            <div className="row h-100">
                {/* LEFT: Upload Panel */}
                <div
                    className="col-md-6 p-4"
                    style={{
                        backgroundColor: "#181818",
                        position: "sticky",
                        top: 0,
                        height: "100vh",
                        color: "#fff",
                    }}
                >
                    <h1 className="mb-4">📘 LMS AI Quiz Generator</h1>

                    <div className="mb-3">
                        <input
                            type="file"
                            accept="application/pdf"
                            className="form-control"
                            onChange={(e) => setFile(e.target.files[0])}
                        />
                    </div>

                    <button
                        className="btn btn-primary w-100"
                        onClick={handleUpload}
                        disabled={loading}
                    >
                        {loading ? "Generating..." : "Generate Quiz"}
                    </button>

                    <hr />

                    <p className="mt-4 text-light">
                        Upload a PDF file to automatically generate quiz questions using AI.
                    </p>

                    <div className="p-3 bg-primary rounded-3">
                        <p className="mt-4 text-justify">
                            The content is generated by an OpenAI model. Verify answers independently
                            before relying on them.
                        </p>
                    </div>
                </div>

                {/* RIGHT: Quiz Display Panel */}
                <div
                    className="col-md-6 p-4"
                    style={{
                        backgroundColor: "#212121",
                        height: "100vh",
                        overflowY: "auto",
                        color: "#fff",
                    }}
                >
                    <h2 className="mb-4">Generated Quiz</h2>

                    {!quiz || !quiz.questions ? (
                        <p className="text-light">No quiz generated yet.</p>
                    ) : (
                        <div className="row">
                            {quiz.questions.map((q, i) => (
                                <div className="col-12 mb-3" key={i}>
                                    <div className="card shadow-sm border-0">
                                        <div className="card-body">
                                            <h5 className="card-title">
                                                Q{i + 1}: {q.question}
                                            </h5>
                                            <ul className="list-group list-group-flush mb-2">
                                                {Object.entries(q.options).map(([key, value]) => (
                                                    <li className="list-group-item" key={key}>
                                                        <strong>{key.toUpperCase()}.</strong> {value}
                                                    </li>
                                                ))}
                                            </ul>
                                            <p className="text-success mb-0">
                                                <strong>Answer:</strong> {q.correct_answer.toUpperCase()} —{" "}
                                                {q.options[q.correct_answer]}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}

export default QuizGenerator;
